apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uoe90f7dy-nodejs 
  janus-idp.io/tekton: uoe90f7dy-nodejs
  backstage.io/kubernetes-id: uoe90f7dy-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uoe90f7dy-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml