apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uoe90f7dy-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uoe90f7dy-nodejs 
  name: uoe90f7dy-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: uoe90f7dy-nodejs 
